<a href="https://colab.research.google.com/github/kalisettyprasanna72-alt/Bootcamp-Track-5-Data-Intelligence-AI/blob/main/Track_5_Day_1_Bootcamp_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment: The Satellite Weather Image Grid Fixer
• Task: Imagine a satellite sends weather data as a messy 24 \times 24 grid of numbers. Write a program to reshape it into a 3D matrix representing morning, afternoon, and night blocks. Use a Boolean mask to find all temperature spots that are dangerously high, and replace those bad readings with the average temperature of the entire grid in one step without using any loops.


In [ ]:
# Import NumPy library for numerical operations
import numpy as np

In [ ]:
# Create a 24x24 grid with random temperature values
# Values range from 10°C to 49°C
data = np.random.randint(10, 50, size=(24, 24))

print(data)

[[13 43 12 25 43 22 21 13 14 25 25 14 49 27 44 38 31 30 18 23 41 24 18 18]
 [16 35 10 13 25 35 10 27 18 24 11 33 47 49 22 35 45 12 28 32 16 11 38 36]
 [32 16 39 22 26 16 24 17 34 41 38 34 17 28 33 45 11 43 11 30 43 34 28 17]
 [43 26 43 15 17 28 25 16 32 26 13 16 25 16 38 11 31 32 19 32 23 42 14 35]
 [46 34 15 18 15 14 15 30 21 43 33 20 19 39 10 14 23 13 13 26 19 39 44 31]
 [47 47 47 19 43 38 21 13 49 35 43 44 31 41 47 24 30 44 41 26 35 48 42 36]
 [46 31 40 32 22 41 45 47 47 15 34 21 33 23 40 26 44 37 12 39 12 44 30 31]
 [17 27 24 39 32 41 28 38 19 45 27 44 26 24 41 24 29 15 16 22 14 34 10 21]
 [12 12 48 29 34 49 34 21 32 38 21 38 43 26 33 37 49 15 38 17 44 21 10 15]
 [15 33 23 44 16 32 20 34 33 26 30 39 43 14 15 42 35 18 26 36 16 14 46 27]
 [29 33 13 40 20 34 13 18 41 18 39 45 17 37 20 14 21 40 47 38 17 28 15 12]
 [11 10 27 25 42 30 23 18 21 32 24 35 43 23 14 14 31 32 25 21 25 37 37 37]
 [27 38 46 30 10 44 32 42 24 38 34 35 32 46 32 10 46 25 15 37 41 40 20 49]
 [30 14 13 32 22 29 12 38

In [ ]:
# Reshape the 2D grid into a 3D array
# Morning, Afternoon, Night
data_3d = data.reshape(3, 8, 24)

print(data_3d.shape)

(3, 8, 24)


In [ ]:
# Set dangerous temperature threshold
threshold = 40

# Create Boolean mask
mask = data_3d > threshold

print(mask)

[[[False  True False False  True False False False False False False
   False  True False  True False False False False False  True False
   False False]
  [False False False False False False False False False False False
   False  True  True False False  True False False False False False
   False False]
  [False False False False False False False False False  True False
   False False False False  True False  True False False  True False
   False False]
  [ True False  True False False False False False False False False
   False False False False False False False False False False  True
   False False]
  [ True False False False False False False False False  True False
   False False False False False False False False False False False
    True False]
  [ True  True  True False  True False False False  True False  True
    True False  True  True False False  True  True False False  True
    True False]
  [ True False False False False  True  True  True  True False False
   Fals

In [ ]:
# Set dangerous temperature threshold
threshold = 40

# Create Boolean mask
mask = data_3d > threshold

print(mask)

[[[False  True False False  True False False False False False False
   False  True False  True False False False False False  True False
   False False]
  [False False False False False False False False False False False
   False  True  True False False  True False False False False False
   False False]
  [False False False False False False False False False  True False
   False False False False  True False  True False False  True False
   False False]
  [ True False  True False False False False False False False False
   False False False False False False False False False False  True
   False False]
  [ True False False False False False False False False  True False
   False False False False False False False False False False False
    True False]
  [ True  True  True False  True False False False  True False  True
    True False  True  True False False  True  True False False  True
    True False]
  [ True False False False False  True  True  True  True False False
   Fals

In [ ]:
# Calculate global average temperature
avg_temp = data_3d.mean()

# Replace dangerous temperatures with average
data_3d[mask] = avg_temp

print("Processed Data:\n", data_3d)
print("\nAverage Temperature:", avg_temp)

Processed Data:
 [[[13 29 12 25 29 22 21 13 14 25 25 14 29 27 29 38 31 30 18 23 29 24 18
   18]
  [16 35 10 13 25 35 10 27 18 24 11 33 29 29 22 35 29 12 28 32 16 11 38
   36]
  [32 16 39 22 26 16 24 17 34 29 38 34 17 28 33 29 11 29 11 30 29 34 28
   17]
  [29 26 29 15 17 28 25 16 32 26 13 16 25 16 38 11 31 32 19 32 23 29 14
   35]
  [29 34 15 18 15 14 15 30 21 29 33 20 19 39 10 14 23 13 13 26 19 39 29
   31]
  [29 29 29 19 29 38 21 13 29 35 29 29 31 29 29 24 30 29 29 26 35 29 29
   36]
  [29 31 40 32 22 29 29 29 29 15 34 21 33 23 40 26 29 37 12 39 12 29 30
   31]
  [17 27 24 39 32 29 28 38 19 29 27 29 26 24 29 24 29 15 16 22 14 34 10
   21]]

 [[12 12 29 29 34 29 34 21 32 38 21 38 29 26 33 37 29 15 38 17 29 21 10
   15]
  [15 33 23 29 16 32 20 34 33 26 30 39 29 14 15 29 35 18 26 36 16 14 29
   27]
  [29 33 13 40 20 34 13 18 29 18 39 29 17 37 20 14 21 40 29 38 17 28 15
   12]
  [11 10 27 25 29 30 23 18 21 32 24 35 29 23 14 14 31 32 25 21 25 37 37
   37]
  [27 38 29 30 10 29 32 29 24 38 